/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProjectsIndexImport } from './routes/projects/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as ProjectsProjectIdViewImport } from './routes/projects/$projectId/view'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsIndexRoute = ProjectsIndexImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const ProjectsProjectIdViewRoute = ProjectsProjectIdViewImport.update({
  id: '/projects/$projectId/view',
  path: '/projects/$projectId/view',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexImport
      parentRoute: typeof rootRoute
    }
    '/projects/$projectId/view': {
      id: '/projects/$projectId/view'
      path: '/projects/$projectId/view'
      fullPath: '/projects/$projectId/view'
      preLoaderRoute: typeof ProjectsProjectIdViewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/view': typeof ProjectsProjectIdViewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/view': typeof ProjectsProjectIdViewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/view': typeof ProjectsProjectIdViewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/projects' | '/projects/$projectId/view'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/projects' | '/projects/$projectId/view'
  id: '__root__' | '/' | '/about/' | '/projects/' | '/projects/$projectId/view'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsProjectIdViewRoute: typeof ProjectsProjectIdViewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsProjectIdViewRoute: ProjectsProjectIdViewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about/",
        "/projects/",
        "/projects/$projectId/view"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/projects/": {
      "filePath": "projects/index.tsx"
    },
    "/projects/$projectId/view": {
      "filePath": "projects/$projectId/view.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
